<script lang="ts">
  import { onMount } from 'svelte';
  import BoardScene from './BoardScene.svelte';
  import type { LiveStore } from './live';
  import type { PositionRange } from './types';
  import { selectedRanges, solvePositions, type RangeSource } from './positions';
  let { live, nodeCount, revision }: { live:LiveStore; nodeCount:number; revision:number }=$props();
  type Snapshot={id:string;name:string;created:string;ranges:PositionRange[]};
  let mode:'live'|'snapshot'=$state('live'),source:RangeSource=$state('smoothed'),edgeMode:'residual'|'neutral'|'hidden'=$state('residual'),origin=$state(0),xAxis=$state(1),xyPlane=$state(2),above=$state(3),snapshots=$state<Snapshot[]>([]),snapshotId=$state('');
  const nodes=$derived(Array.from({length:nodeCount},(_,i)=>i));
  const liveRanges=$derived.by(()=>{void revision;return Array.from(live.positionRanges.values()).map((item)=>({...item,window:item.window.slice()}));});
  const snapshot=$derived(snapshots.find((item)=>item.id===snapshotId));
  const rangeState=$derived(mode==='snapshot'&&snapshot?snapshot.ranges:liveRanges);
  const ranges=$derived(selectedRanges(rangeState,source));
  const solution=$derived(solvePositions(nodeCount,ranges,[origin,xAxis,xyPlane],above));
  onMount(()=>{try{snapshots=JSON.parse(sessionStorage.getItem('heimdall-position-snapshots')??'[]');snapshotId=snapshots.at(-1)?.id??''}catch{snapshots=[]}});
  function saveSnapshots(){sessionStorage.setItem('heimdall-position-snapshots',JSON.stringify(snapshots))}
  function capture(){const created=new Date().toISOString(),item={id:`${Date.now()}`,name:`Snapshot ${snapshots.length+1} · ${created.slice(11,19)}`,created,ranges:liveRanges};snapshots=[...snapshots,item];snapshotId=item.id;mode='snapshot';saveSnapshots()}
  function removeSnapshot(){snapshots=snapshots.filter((item)=>item.id!==snapshotId);snapshotId=snapshots.at(-1)?.id??'';if(!snapshotId)mode='live';saveSnapshots()}
  const pct=(value:number)=>`${Math.round(value*100)}%`;
</script>
<section class="positions-layout">
  <div class="position-controls panel">
    <div class="control-row"><div class="segmented"><button class:active={mode==='live'} onclick={()=>mode='live'}>LIVE</button><button class:active={mode==='snapshot'} onclick={()=>mode='snapshot'} disabled={!snapshots.length}>SNAPSHOT</button></div><button class="capture" onclick={capture}>TAKE SNAPSHOT</button></div>
    <label>RANGE SOURCE<select bind:value={source}><option value="raw">DS-TWR raw</option><option value="smoothed">DS-TWR smoothed</option><option value="ultra">DS-TWR ultra smoothed</option></select></label>
    {#if mode==='snapshot'}<label>SNAPSHOT<select bind:value={snapshotId}>{#each snapshots as item}<option value={item.id}>{item.name}</option>{/each}</select></label><button class="remove" onclick={removeSnapshot}>DELETE SNAPSHOT</button>{/if}
    <fieldset><legend>COORDINATE FRAME</legend><label>ORIGIN<select bind:value={origin}>{#each nodes as node}<option value={node} disabled={node===xAxis||node===xyPlane||node===above}>N{node}</option>{/each}</select></label><label>+X REFERENCE<select bind:value={xAxis}>{#each nodes as node}<option value={node} disabled={node===origin||node===xyPlane||node===above}>N{node}</option>{/each}</select></label><label>+XY REFERENCE<select bind:value={xyPlane}>{#each nodes as node}<option value={node} disabled={node===origin||node===xAxis||node===above}>N{node}</option>{/each}</select></label><label>ABOVE PLANE (+Z)<select bind:value={above}>{#each nodes as node}<option value={node} disabled={node===origin||node===xAxis||node===xyPlane}>N{node}</option>{/each}</select></label></fieldset>
    <fieldset><legend>EDGES</legend><div class="segmented edge-mode"><button class:active={edgeMode==='residual'} onclick={()=>edgeMode='residual'}>RESIDUAL</button><button class:active={edgeMode==='neutral'} onclick={()=>edgeMode='neutral'}>NEUTRAL</button><button class:active={edgeMode==='hidden'} onclick={()=>edgeMode='hidden'}>HIDDEN</button></div></fieldset>
  </div>
  <article class="scene-panel panel"><header><span>RECONSTRUCTED BOARD GEOMETRY</span><b>{mode.toUpperCase()} · {source.replace('ultra','ultra smooth').toUpperCase()}</b></header><div><BoardScene positions={solution.positions} edges={solution.edges} {edgeMode} /></div></article>
  <aside class="diagnostics panel"><header><span>FIT DIAGNOSTICS</span><b class:warn={solution.status!=='SOLVED'}>{solution.status}</b></header><dl><dt>RMSE</dt><dd>{(solution.rmse*100).toFixed(2)} cm</dd><dt>PAIR COVERAGE</dt><dd>{solution.edges.length}/{nodeCount*(nodeCount-1)/2} · {pct(solution.coverage)}</dd><dt>CONFIDENCE</dt><dd>{pct(solution.confidence)}</dd><dt>FRAME</dt><dd>N{origin} origin · N{xAxis} +X<br>N{xyPlane} +XY · N{above} +Z</dd></dl><div class="edge-list">{#each solution.edges.slice().sort((a,b)=>Math.abs(b.residual)-Math.abs(a.residual)) as edge}<div><span>N{edge.a}↔N{edge.b}</span><b>{edge.measured.toFixed(3)} m</b><i class:bad={Math.abs(edge.residual)>.1}>{edge.residual>=0?'+':''}{(edge.residual*100).toFixed(1)} cm</i></div>{/each}</div></aside>
</section>
<style>
  .positions-layout{display:grid;grid-template-columns:230px minmax(0,1fr) 250px;gap:7px;min-height:0}.panel{min-height:0}.position-controls{padding:10px;overflow-y:auto}.control-row{display:flex;gap:6px;margin-bottom:10px}.segmented{display:flex;border:1px solid #304147;padding:2px}.segmented button,.capture,.remove{border:0;background:transparent;color:#718188;padding:6px 9px;font:9px DM Mono,monospace}.segmented button.active,.capture{background:#45e0c1;color:#07110f}.capture{margin-left:auto}.remove{width:100%;border:1px solid #5a4230;color:#f4bd62;margin-bottom:10px}.position-controls>label,.position-controls fieldset label{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:9px 0;color:#91a1a6;font:8px DM Mono,monospace}.position-controls select{width:120px;padding:5px}.position-controls fieldset{margin:12px 0;padding:8px;border:1px solid #26373d}.position-controls legend{color:#45e0c1;padding:0 4px;font:8px DM Mono,monospace}.edge-mode button{padding:5px}.scene-panel{display:grid;grid-template-rows:36px minmax(0,1fr)}.scene-panel>header,.diagnostics>header{height:36px;padding:0 10px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #233138;color:#91a1a6;font:9px DM Mono,monospace}.scene-panel>header b,.diagnostics>header b{color:#45e0c1;font-weight:400}.scene-panel>div{min-height:0}.diagnostics{overflow:hidden}.diagnostics dl{display:grid;grid-template-columns:1fr auto;gap:8px;margin:0;padding:12px;border-bottom:1px solid #233138;font:9px DM Mono,monospace}.diagnostics dt{color:#718188}.diagnostics dd{margin:0;text-align:right}.warn{color:#f4bd62!important}.edge-list{height:calc(100% - 150px);overflow:auto;padding:4px 10px}.edge-list div{display:grid;grid-template-columns:1fr auto auto;gap:8px;padding:7px 0;border-bottom:1px solid #1b282d;font:8px DM Mono,monospace}.edge-list span{color:#a9b8bb}.edge-list b{font-weight:400}.edge-list i{color:#45e0c1;font-style:normal}.edge-list i.bad{color:#f4bd62}@media(max-width:900px){.positions-layout{grid-template-columns:110px minmax(0,1fr)}.position-controls{padding:6px}.position-controls label{display:block!important}.position-controls select{display:block;width:100%;margin-top:3px}.control-row{display:block}.capture{width:100%;margin-top:4px}.diagnostics{display:none}.edge-mode{display:block}.edge-mode button{width:100%}}
</style>
