<script lang="ts">
  import { onMount } from 'svelte';
  import { projectBoardPoint, type PositionEdge, type Vec3 } from './positions';
  let { positions, edges, edgeMode = 'residual' }: { positions:Vec3[]; edges:PositionEdge[]; edgeMode:'residual'|'neutral'|'hidden' }=$props();
  let canvas:HTMLCanvasElement,labels=$state<{id:number;x:number;y:number;visible:boolean}[]>([]),axisLabels=$state<{name:string;x:number;y:number;visible:boolean}[]>([]),yaw=0,pitch=-.65,zoom=1,dirty=true,framedNodeCount=0,viewCenter:Vec3|undefined,viewSpan=1;
  $effect(()=>{positions;edges;edgeMode;if(positions.length!==framedNodeCount){framedNodeCount=positions.length;viewCenter=undefined}dirty=true;});
  const color=(hex:string)=>[0,1,2].map((i)=>parseInt(hex.slice(1+i*2,3+i*2),16)/255);
  onMount(()=>{
    const gl=canvas.getContext('webgl2',{alpha:false,antialias:true});if(!gl)return;
    const shader=(type:number,source:string)=>{const value=gl.createShader(type)!;gl.shaderSource(value,source);gl.compileShader(value);return value},program=gl.createProgram()!;
    gl.attachShader(program,shader(gl.VERTEX_SHADER,'#version 300 es\nin vec2 p;in vec3 c;out vec3 vc;uniform float size;void main(){gl_Position=vec4(p,0.,1.);gl_PointSize=size;vc=c;}'));
    gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'#version 300 es\nprecision mediump float;in vec3 vc;out vec4 o;void main(){o=vec4(vc,1.);}'));
    gl.linkProgram(program);const p=gl.getAttribLocation(program,'p'),c=gl.getAttribLocation(program,'c'),size=gl.getUniformLocation(program,'size'),buffer=gl.createBuffer()!;
    const project=(point:Vec3,w:number,h:number,center:Vec3,span:number)=>{const {nx,ny,factor}=projectBoardPoint(point,center,span,yaw,pitch,zoom);return{nx,ny,x:(nx*.5+.5)*w,y:(.5-ny*.5)*h,visible:factor>0&&Math.abs(nx)<1.2&&Math.abs(ny)<1.2}};
     const render=()=>{const d=Math.min(devicePixelRatio,2),w=Math.max(1,Math.floor(canvas.clientWidth*d)),h=Math.max(1,Math.floor(canvas.clientHeight*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(.043,.067,.082,1);gl.clear(gl.COLOR_BUFFER_BIT);if(!positions.length)return;if(!viewCenter){const min={x:Math.min(...positions.map(q=>q.x)),y:Math.min(...positions.map(q=>q.y)),z:Math.min(...positions.map(q=>q.z))},max={x:Math.max(...positions.map(q=>q.x)),y:Math.max(...positions.map(q=>q.y)),z:Math.max(...positions.map(q=>q.z))};viewCenter={x:(min.x+max.x)/2,y:(min.y+max.y)/2,z:(min.z+max.z)/2};viewSpan=Math.max(max.x-min.x,max.y-min.y,max.z-min.z,.5)*.7}const center=viewCenter,span=viewSpan,projected=positions.map((q)=>project(q,w/d,h/d,center,span));
      const vertices:number[]=[];const line=(a:Vec3,b:Vec3,hex:string)=>{const u=project(a,w,h,center,span),v=project(b,w,h,center,span),rgb=color(hex);vertices.push(u.nx,u.ny,...rgb,v.nx,v.ny,...rgb)};
      const extent=Math.max(1,Math.ceil(Math.max(...positions.flatMap(q=>[Math.abs(q.x),Math.abs(q.y)]))));for(let i=-extent;i<=extent;i++){line({x:-extent,y:i,z:0},{x:extent,y:i,z:0},'#172328');line({x:i,y:-extent,z:0},{x:i,y:extent,z:0},'#172328')}line({x:0,y:0,z:0},{x:extent,y:0,z:0},'#f4bd62');line({x:0,y:0,z:0},{x:0,y:extent,z:0},'#45e0c1');line({x:0,y:0,z:0},{x:0,y:0,z:extent},'#b995ff');
      if(edgeMode!=='hidden'){const residualScale=Math.max(.01,...edges.map(e=>Math.abs(e.residual)));for(const edge of edges){const hex=edgeMode==='neutral'?'#52636a':edge.residual>=0?(Math.abs(edge.residual)/residualScale>.5?'#f4bd62':'#806d4c'):(Math.abs(edge.residual)/residualScale>.5?'#b995ff':'#685c7d');line(positions[edge.a],positions[edge.b],hex)}}
      gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STREAM_DRAW);gl.enableVertexAttribArray(p);gl.enableVertexAttribArray(c);gl.vertexAttribPointer(p,2,gl.FLOAT,false,20,0);gl.vertexAttribPointer(c,3,gl.FLOAT,false,20,8);gl.uniform1f(size,1);gl.drawArrays(gl.LINES,0,vertices.length/5);
       const points:number[]=[];for(const q of projected)points.push(q.nx,q.ny,...color('#45e0c1'));gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(points),gl.STREAM_DRAW);gl.uniform1f(size,12*d);gl.drawArrays(gl.POINTS,0,positions.length);labels=projected.map((q,id)=>({id,x:q.x,y:q.y,visible:q.visible}));axisLabels=[['+X',{x:extent,y:0,z:0}],['+Y',{x:0,y:extent,z:0}],['+Z',{x:0,y:0,z:extent}]].map(([name,point])=>{const q=project(point as Vec3,w/d,h/d,center,span);return{name:name as string,x:q.x,y:q.y,visible:q.visible}});
    };
    let raf=0;const loop=()=>{if(dirty){render();dirty=false}raf=requestAnimationFrame(loop)};loop();const resize=new ResizeObserver(()=>dirty=true);resize.observe(canvas);
    let dragging=false,lastX=0,lastY=0;const down=(e:PointerEvent)=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)},move=(e:PointerEvent)=>{if(!dragging)return;yaw+=(e.clientX-lastX)*.008;pitch=Math.max(-Math.PI/2,Math.min(Math.PI/2,pitch+(e.clientY-lastY)*.008));lastX=e.clientX;lastY=e.clientY;dirty=true},up=()=>dragging=false,wheel=(e:WheelEvent)=>{e.preventDefault();zoom=Math.max(.25,Math.min(5,zoom*Math.exp(-e.deltaY*.001)));dirty=true};canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('wheel',wheel,{passive:false});return()=>{cancelAnimationFrame(raf);resize.disconnect();gl.deleteBuffer(buffer);gl.deleteProgram(program)};
  });
   function reset(){yaw=0;pitch=-.65;zoom=1;viewCenter=undefined;dirty=true}
   function top(){yaw=0;pitch=-Math.PI/2;zoom=1;viewCenter=undefined;dirty=true}
</script>
<div class="scene"><canvas bind:this={canvas} aria-label="Interactive 3D board positions"></canvas><div class="labels">{#each labels as item}{#if item.visible}<span style={`left:${item.x}px;top:${item.y}px`}>N{item.id}</span>{/if}{/each}{#each axisLabels as item}{#if item.visible}<span class="axis" style={`left:${item.x}px;top:${item.y}px`}>{item.name}</span>{/if}{/each}</div><div class="hint">DRAG ORBIT · WHEEL ZOOM</div><div class="view-buttons"><button onclick={top}>TOP +Z</button><button onclick={reset}>RESET 3D</button></div></div>
<style>
  .scene{position:relative;width:100%;height:100%;min-height:0;overflow:hidden;background:#0b1115}canvas{display:block;width:100%;height:100%;cursor:grab;touch-action:none}.labels{position:absolute;inset:0;pointer-events:none}.labels span{position:absolute;transform:translate(-50%,-150%);padding:2px 4px;background:#071014c9;color:#dbe5e7;font:9px DM Mono,monospace;border:1px solid #31524f}.labels span.axis{color:#f4bd62;border-color:#6b5732;font-weight:700}.hint{position:absolute;left:8px;bottom:7px;color:#61757b;font:8px DM Mono,monospace}.view-buttons{position:absolute;right:8px;bottom:7px;display:flex;gap:5px}.view-buttons button{border:1px solid #385056;background:#0b1215;color:#9fb0b4;padding:5px 7px;font:8px DM Mono,monospace}
</style>
